/** This file is automatically generated, do not edit it! **/

import {Injectable} from "@angular/core";

@Injectable()
export class GettextStrings {
    getStrings() {
        return {"de":{},"es":{},"fr":{},"it":{},"ja":{},"pl":{},"pt-br":{}};
    }
}